export const categoryTypes = {
    GETONE_REQUEST: 'CATEGORY_GETONE_REQUEST',
    GETONE_SUCCESS: 'CATEGORY_GETONE_SUCCESS',
    GETONE_FAILURE: 'CATEGORY_GETONE_FAILURE',

    GETALL_REQUEST: 'CATEGORY_GETALL_REQUEST',
    GETALL_SUCCESS: 'CATEGORY_GETALL_SUCCESS',
    GETALL_FAILURE: 'CATEGORY_GETALL_FAILURE',
};
