export const collectionTypes = {
    GETONE_REQUEST: 'COLLECTION_GETONE_REQUEST',
    GETONE_SUCCESS: 'COLLECTION_GETONE_SUCCESS',
    GETONE_FAILURE: 'COLLECTION_GETONE_FAILURE',

    GETALL_REQUEST: 'COLLECTION_GETALL_REQUEST',
    GETALL_SUCCESS: 'COLLECTION_GETALL_SUCCESS',
    GETALL_FAILURE: 'COLLECTION_GETALL_FAILURE',

    CREATE_SUCCESS: 'COLLECTION_CREATE_SUCCESS',
    CREATE_FAILURE: 'COLLECTION_CREATE_FAILURE',

    DELETE_REQUEST: 'COLLECTION_DELETE_REQUEST',
    DELETE_SUCCESS: 'COLLECTION_DELETE_SUCCESS',
    DELETE_FAILURE: 'COLLECTION_DELETE_FAILURE'
};

export const itemTypes = {
    GETONE_SUCCESS: 'ITEM_GETONE_SUCCESS',
    GETONE_FAILURE: 'ITEM_GETONE_FAILURE'
}
