"""empty message

Revision ID: 8cf24151fcd5
Revises: fada4a37a943
Create Date: 2020-10-28 10:56:27.745303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf24151fcd5'
down_revision = 'fada4a37a943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('condition', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'condition')
    # ### end Alembic commands ###
