"""Removed first and last name fields from user

Revision ID: fada4a37a943
Revises: 417d4ab56c8f
Create Date: 2020-10-07 09:40:37.215554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fada4a37a943'
down_revision = '417d4ab56c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'firstName')
    op.drop_column('users', 'lastName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('firstName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
